### ISSUE TITLE
gwnet readme example won't work

### ISSUE THREAD

**Issue by jonasmmiguel** [xumwen/spatial-temporal-forecast#5]
First of all, congrats on the great project! Thank you for making this repo public!

When trying to run the readme example
`python main.py -m gwnet -d metr`

I'm incurring in the following error

> RuntimeError: Given groups=1, weight of size [32, 1722, 1, 1], expected input[64, 2, 207, 13] to have 1722 channels, but got 2 channels instead

What adjustments would you recommend me to do?

**Comment by xumwen** [comment]
Thanks for your attention and using of this repo!

GWNET dose not work because its' initial parameter order is different from STGCN or TGCN.

I have added an parameter list **kwargs in GWNET's initialization and specified parameters' name in nets' initialization.

It should works now.

**Comment by machml** [comment]
Thank you so much, @xumwen!

**Comment by jonasmmiguel** [comment]
@xumwen, I want to give credits in my thesis for this great development on pytorch and pytorch-lighning. If you have a bibtex reference for this repo, please let me know!
