### ISSUE TITLE
Bibtex reference? :)

### ISSUE THREAD

**Issue by machml** [xumwen/spatial-temporal-forecast#7]
Hi!
Thanks again for the effort putting this repo together and for helping me use it!
I'm currently citing this repo as a website. Let me know in case you have a bibtex reference for it.

**Comment by xumwen** [comment]
Feel free to cite the repo.

We build the repo when working at MSRA and maybe you can mention it.

:)

**Comment by machml** [comment]
Alright!

That's the entry I'm currently using. Let me know if you'd have something adjusted.

@misc{xumwen2020spatial,
  author = {Xumeng, Wen},
  title = {Baseline models for Spatio-Temporal Forecasting},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/xumwen/spatial-temporal-forecast}},
  commit = {cf4904010488512d22690de0c129f7a5fb45152e}
}
